### ISSUE TITLE
Walkthrough using samples from the mic?

### ISSUE THREAD

**Issue by Justyouraveragehomie** [Nanobot567/CS-16#3] opened 2023-11-13 06:53 UTC
Hey there, just been checking out your project. 
I don't own a Playdate yet, but if I did would use it for sampling and sequencing using stuff from the mic. 

As a feature request, could you do a walkthrough using real-time recording of samples using the mic?
For instance, using your voice for kicks, hh's, snares? Or sampling anything that might resemble these.
(also using the sample editor you mention in your last walkthough.....hoping its a nice big waveform view with loop points that you can adjust using the crank?) 

Is there stuff like swing, quantization? -
For another feature request...which would sell me on this for sure is, could I tap the A or B pad to record in my rhythm following a metronome? This would be more natural as opposed to plugging in the notes for me, but having both would be good.  

Cheers!

**Comment by Nanobot567** [comment] 2023-11-13 14:38
Hey! Thanks for giving CS-16 a look!

Would you rather the walkthrough be a video or a segment in the manual? I can do either of these, but I was wondering what would be more helpful to you.

There is not swing yet, but I'll keep it in mind! When I figure out a way to pull it off, I'll be sure to add it in.

The waveform view and recording via the A/B button will be available in the next update :)

**Comment by Justyouraveragehomie** [comment] 2023-11-13 17:49
I think in a video would be awesome. I think I meant trim points as opposed to loop points (maybe its the same thing) for a waveform view, like using A for the right side and B for the left side of the sample, and then adjusting the start+end points of both using the crank, something like that?  
Recording via the A/B button would be great....something better though, what about assigning drum samples to the A+B buttons, as well as the D-pad? 
I don't know what the d-pad feels like, but could you essentially drum in your rhythm (to the metronome) using all 6 buttons? You wouldn't need anymore than 6 samples anyways.  Like instead of using your thumbs, you could place the playdate on a hard surface and tap the buttons?

**Comment by Nanobot567** [comment] 2023-11-13 21:48
Alright, I'll put together a video demonstrating sampling sometime soon! 👍

About trimming the waveform using A and B, I think that the d-pad swapping the side of the sample to trim is better than A/B, simply because it seems more intuitive (but what do I know haha). And the crank already trims the sample so I'll just keep that the same :)

By the way CS-16 is structured internally and how the UI is, using multiple buttons to record to multiple tracks at once could be possible but would require some extra configuration on the user's end (like the user would have to select the tracks that are mapped to A/B/up/down/left/right in settings).

The sample rate is 16 bit, but adding a menu item to swap it with 8 bit sounds like a good idea, I might add this in too!

**Comment by Justyouraveragehomie** [comment] 2023-11-14 19:47
Awesome! Oh youre definitely right, side to side with the d-pad makes way more sense haha.  
Wouldn't it be one track though? Yeah I was thinking assigning samples to A/B/up/down/left/right in settings prior to recording a track, that way you could layout where you wanted your drum samples depending on the ergonomics of peoples hands. 
Thanks for being so responsive, you should post over to https://www.reddit.com/r/PlaydateDeveloper to get feedback from people who actually own a Playdate! 
Yes definitely curious to hear how the samples sound from the mic assigned to the buttons.

**Comment by Nanobot567** [comment] 2023-11-15 01:10
> If you do end up doing a video, could it be a video of the actual playdate in realtime?

Sure!

Each track in CS-16 can be assigned to a waveform or sample, but only one at a time, so multiple drums on one track would require some behind-the-scenes changes which may be more trouble than it's worth (and the track could be difficult to edit if this was the way it worked now). Sorry about this. I will say that if CS-16 gets rewritten / redesigned in the future I'll consider changing that!

> Thanks for being so responsive :)

No problem! Just trying to make sure people are happy with the stuff I'm making XD

By the way, it may take a couple weeks for me to actually add all of the features you requested to CS-16, I'm pretty slammed with school at the moment. I'll get it done as soon as I can, though!

**Comment by Nanobot567** [comment] 2023-11-22 23:11
I finished the real-time recording feature! There are options in settings to change the track that each button is mapped to, as well as quantization! (As you could probably tell in the video I pretty much needed it to tap it in correctly haha)

Getting started on the waveform view now. Just so you know this may take me a bit longer to finish :)

https://github.com/Nanobot567/CS-16/assets/70984367/985d861b-f5e7-46c9-b6cb-2ba9b4387e1d

**Comment by Justyouraveragehomie** [comment] 2023-11-23 02:43
So fast!! Im super impressed. So you can increase the quantization to be like 1/4, 1/8, 1/16, 1/32, 1/64? (1/64 seems a little unnecessary, but maybe if you like super fine timing thats still quantized)  + swing option!

**Comment by Nanobot567** [comment] 2023-11-23 05:35
Yep, the quantization can be 1/32, 1/16, or 1/8. Since CS-16 (and the synth functions provided in the SDK) are completely step based, 1/64 is currently impossible.

The number in the bottom left is the current sequencer step. And yeah, BPM is a setting :)

I see what you're saying for the visualization! If I can I'll rework the pattern drawing function to have this happen.

To remove a note from the track while recording you just press the same button at the same time to toggle it off.

**Comment by Justyouraveragehomie** [comment] 2023-11-25 22:18
Regarding the sample rate of the playdate in khz, do you know if there is a range that it records at?

**Comment by Nanobot567** [comment] 2023-11-26 21:23
I'm not sure! I think that the condenser microphone should pick up most frequencies that matter, though. If that isn't good enough you can always just send the audio file over to your Playdate.

**Comment by Justyouraveragehomie** [comment] 2023-11-27 03:13
I was actually thinking the opposite, less khz, for a crunchier sound. ;) Though maybe an 8-bit option would do the trick.

**Comment by Nanobot567** [comment] 2023-12-04 16:31
Just thought I'd give you a little update on my progress so far! Currently, the waveform looks like this:
![wv](https://github.com/Nanobot567/CS-16/assets/70984367/077ea270-b457-431a-a448-77a913b1f6b0)

Right now I'm trying to add this same waveform into the sample trimmer as well, and have it be accurate to the sample.

Regarding the video on sampling with the Playdate, honestly I still haven't gotten around to recording it 😅. I have some cool ideas for it though, so I'll get on that as soon as I can!

(Also, just so you know, samples imported from the computer probably won't have this functionality, since I'm gathering the volume information straight from the Playdate's microphone and getting that info from an audio file would be considerably more difficult. If that's an issue, I'll try to slam together an "audio to playdate image" converter for you :) )

**Comment by Nanobot567** [comment] 2023-12-05 03:22
> There probably is a certain khz that the playdate records at, im assuming its like 16-bit, 44.1khz.

Yeah, that sounds about right!

> Maybe it would be good to add a sample time limit or memory amount? Like a max sample time of 5 seconds per sample or even less?

There's a cap of 5 seconds per sample at the moment. (Should I add a setting to change this?)

> Would be cool to crank in any sample rate from super low up to its max.

That would be pretty awesome! Unfortunately, the Playdate's sample rate is immutable. :/

**Comment by Justyouraveragehomie** [comment] 2023-12-07 18:26
5 seconds sounds good to me!  Ah too bad about the sample rate, thats ok though :)

**Comment by Nanobot567** [comment] 2023-12-10 16:39
I just released version 1.3 of CS-16, with your features included! If you find any issues with the app or you're just not happy with the way I implemented something, feel free to say something :D

**Comment by Justyouraveragehomie** [comment] 2023-12-10 22:10
Amazing work! Did a swing function make it into the release?  
Looking forward to seeing the video :D

**Comment by Nanobot567** [comment] 2023-12-10 22:43
> Amazing work! Did a swing function make it into the release?

Thanks! But nope, couldn't make it work :(

> -a black on white version (instead of white on black) would be easier on my eyeballs, I know this would probably use more battery power

There's a "dark mode" option in settings that can be turned off.

-are you partial to the font? can it be changed to be more clear/modern?

Yep! I actually just added an option in this release to change the font to the default system font.

**Comment by Justyouraveragehomie** [comment] 2023-12-10 23:07
Is the timing stuff in funcs.lua?  I dont understand swing much myself....on my current drum machine its between 0.5 and 0.75. Its something about subdividing the quantization and having triplets...err

**Comment by Nanobot567** [comment] 2023-12-11 00:57
So, almost the entirety of the timing code is in the [Playdate SDK](https://sdk.play.date/2.1.1/Inside%20Playdate.html), and I've essentially just created an interface for all of the synthesizer functions that you see in CS-16. Until the developers include swing in their sequencer, I don't think that it's possible to do without rewriting the entire sequencer portion of the code myself, which would be a massive hassle XD

**Comment by Justyouraveragehomie** [comment] 2023-12-11 01:06
Gotcha. Ahh I see I see....maybe ill reach out to them and ask them to include one :p  
Wonder if it could be done with delay, that sounds tricky though.

**Comment by Justyouraveragehomie** [comment] 2023-12-11 01:25
Is it possible to set a time amount for each step manually by a ratio? Or make each step a "loop"...not sure. 
Sorry for making your thread so long! I think youve got something great here.

**Comment by Nanobot567** [comment] 2023-12-11 02:15
It doesn't seem like it, no.

Don't be sorry, and thank you! I'm really glad you're interested and want to give feedback, it means a lot :)

**Comment by Justyouraveragehomie** [comment] 2023-12-12 19:44
I got a partial answer from Playdate, they said its not a current feature, but they will now look into it.  

From Playdate:

"That being said, I did get some more info on a potential workaround:
There’s also no reason you couldn’t just use a higher resolution and increase your tempo up to match. e.g. if you scale it up by 8x then beats 1/2/3/4 are on position 1/9/17/25 (annoying 1-based arrays..) with no swing, but moving 2 and 4 back to 11 and 27 gives what would be a 62.5% swing in Linn’s system."

**Comment by Justyouraveragehomie** [comment] 2024-04-03 04:02
Hey, any chance to make a video? Also still curious about the swing thing. Cheers :-)

**Comment by Nanobot567** [comment] 2024-04-03 12:14
Hey!! So sorry, honestly I completely forgot about the video 😅. Thanks for reminding me! I'll have tons of time to work on it during June, so I'll definitely have it out by then (and I'll send you a link once it's finished).

About swing, I haven't worked on CS-16 in a WHILE (instead I've been sinking all of my time into a different project). I'll get back on it today or tomorrow and see if that 8x tempo solution works.

Sorry again for keeping you waiting so long, and thanks for checking in!!

**Comment by Nanobot567** [comment] 2024-04-03 19:57
Swing!

https://github.com/Nanobot567/CS-16/assets/70984367/9fa5449b-c2a2-4cd4-b5d1-ac73482ce663

**Comment by Nanobot567** [comment] 2024-04-03 19:58
Swing works!!

https://github.com/Nanobot567/CS-16/assets/70984367/2a928f84-51e0-4a52-86fa-e4b673380c45

**Comment by Justyouraveragehomie** [comment] 2024-04-03 23:05
Damn thats a hot beat, what the heck! Is this at like 60-something in swing, seems like its the hihats? Is the swing able to go from 50 to 75?  Curious to know if itd be able to do like dilla-esque swing.  
Would love to see a version of cs-16 with black on white instead, maybe with a more simple font?

**Comment by Nanobot567** [comment] 2024-04-03 23:31
> Damn thats a hot beat, what the heck!

Thanks, haha :sweat_smile: 

> Is this at like 60-something in swing, seems like its the hihats? Is the swing able to go from 50 to 75?

Not entirely sure what the actual percentage of swing it's at, I'll see if I can do some on-the-fly math to get it. The swing can go pretty far, 5 steps (probably 1/64 notes?) forward and backward in the sequence. Any more makes the sound blend together in my opinion. Maybe I should increase it?

> Would love to see a version of cs-16 with black on white instead, maybe with a more simple font?

White on black already exists! :wink:

![lightmode](https://github.com/Nanobot567/CS-16/assets/70984367/3244ec3d-3261-4ac9-9df2-ef96a822e880)

As for a simpler font, do you have one in mind?

**Comment by Justyouraveragehomie** [comment] 2024-04-04 01:05
Maybe something similar to this? https://twentyminutemile.itch.io/playout  where its a little more easily readable, not sure if this is doable or not.  
So you can assign the swing to the whole track and separately?  Thatd be super interesting, to have different swing amounts on kick/hh/snare. Curious to see the start and end point action on the recorded samples, assuming its done with the crank. 
Id definitely post to reddit at this rate, maybe some other music makers with playdates will have better hands on suggestions.....I need to get one! Swing options was what was going to swing me to get it, so im stoked to hear it works :p

**Comment by Nanobot567** [comment] 2024-04-04 14:06
Tried out the Rains built-in system font, thoughts?

![newfont](https://github.com/Nanobot567/CS-16/assets/70984367/c236cebe-2f67-4877-b967-537646cd2da6)

> So you can assign the swing to the whole track and separately?

Not at the moment, but since that sounds pretty cool I'm going to go ahead and get per-track swing implemented :P

> Id definitely post to reddit at this rate

I'll post to Reddit once v1.4 is finished! (Haven't been on Reddit in forever, though, haha)

**Comment by Justyouraveragehomie** [comment] 2024-04-04 23:13
Looks good to me! Easier to read in my opinion.

**Comment by Justyouraveragehomie** [comment] 2024-04-06 04:10
Oh I forgot to ask, are you able to tap in the rhythms you want using the dpad and/or a+b buttons?

**Comment by Nanobot567** [comment] 2024-04-06 05:31
Yep! Actually I just fixed that for the newer sequencer not too long ago :)

**Comment by Justyouraveragehomie** [comment] 2024-04-06 17:14
Thats what I was wondering, so does the sequencer look different than above now? If youre tapping the samples in, is there the ability to do completely unquantized?  Because then the samples wouldn't necessarily fit to that grid would they?  Not if their timing is like 1/64 or higher/unquantized and the grid is only 1/16?

**Comment by Nanobot567** [comment] 2024-04-06 18:43
Oh, no, visually the sequencer looks exactly the same, only the backend has changed. There isn't a way to tap in notes that are completely unquantized, but that shouldn't be too hard to add if that's something you'd want in CS-16! I will say that it's extremely difficult to tap in notes on time, though, but maybe that's just a me problem :laughing:

**Comment by Justyouraveragehomie** [comment] 2024-04-07 00:49
Im mostly thinking about quantization, like if you are tapping in a rhythm, is this to a metronome sound? Could it be? 
Im wondering if the grid is limited to 1/16. Or can you choose a grid like 1/8, 1/12, 1/16, 1/24?  If you are tapping and your timing is a little bit off, is the sample snapped to the grid? I think I mean mostly are you able to change the grid size and can you tap to a metronome

**Comment by Nanobot567** [comment] 2024-04-07 01:18
> like if you are tapping in a rhythm, is this to a metronome sound?

Yep, there's a metronome!

> Or can you choose a grid like 1/8, 1/12, 1/16, 1/24?

No, the grid's locked at 1/16.

> If you are tapping and your timing is a little bit off, is the sample snapped to the grid?

Yes! It can either be snapped to every 1/32 note, 1/16 note, or 1/8 note.

**Comment by Nanobot567** [comment] 2024-04-07 01:24
> if you are tapping in a rhythm, is this to a metronome sound?

Yep, there's a metronome!

> Or can you choose a grid like 1/8, 1/12, 1/16, 1/24?

It's limited to 1/32.

> If you are tapping and your timing is a little bit off, is the sample snapped to the grid?

Yes! It can either be snapped to every 1/8 note, 1/16 note, or 1/32 note.

**Comment by Justyouraveragehomie** [comment] 2024-04-07 02:11
Ok gotcha! Yeah that sounds perfect if its limited to 1/32.

**Comment by Nanobot567** [comment] 2024-04-07 03:20
Honestly I'm not 100% sure what you mean, but here, I'll just send you a couple GIFs of what recording looks like so you can see for yourself, haha. Sorry I'm not on the same page :sweat_smile:

(These are all just me spamming the A button randomly.)

1/32
![REC_1q](https://github.com/Nanobot567/CS-16/assets/70984367/664a98a7-1b26-4496-8464-4850f3522841)

1/16
![REC_2q](https://github.com/Nanobot567/CS-16/assets/70984367/18a49b14-6c5e-412e-8a65-4f85b0f6a433)

1/8
![REC_3q](https://github.com/Nanobot567/CS-16/assets/70984367/cf17345a-ba41-4837-ba2b-bb7ca3543744)

**Comment by Justyouraveragehomie** [comment] 2024-04-07 03:48
Ok I think I understand, is the order going from the first 16 squares then underneath to the next 16 squares below?
If so then that makes sense, I gather 32 squares across the screen wouldn't fit? 
If you can get 32 squares across the screen, then you could put the name of the input sample (like sample 1) above each row of 32 squares. 
Then when youre tapping in the notes into each grid you could preselect 1/8, 1/16 or 1/32 and the notes would fall in the 32 squares depending.  
I might also be an idiot

**Comment by Justyouraveragehomie** [comment] 2024-04-07 03:57
Wait, or maybe have 32 squares across but make them longer heightwise and then just put the names of the buttons like A or B to fall within the same square. That would be way better

**Comment by Nanobot567** [comment] 2024-04-07 04:00
> is the order going from the first 16 squares then underneath to the next 16 squares below?

Yep!

> If you can get 32 squares across the screen, then you could put the name of the pad above each row of 32 squares.

Ohhhh, I see what you mean. I think at the Playdate's resolution of 400 x 240 pixels, smaller grid steps would be close to unreadable. And personally I never need the name of the sample, there's a "preview sound" button in the instrument editor \:P

> I might also be an idiot

Nah, you're not an idiot, lol

> Wait, or maybe have 32 squares across but make them longer heightwise and then just put the names of the buttons like A or B to fall within the same square.

Are you talking about specifically the recording mode, or the pattern editor in its entirety? Either way, yeah, I might run out of room :laughing:

**Comment by Justyouraveragehomie** [comment] 2024-04-07 04:08
Ah not enough room then.  I think you could fit 32 squares across though? You wouldn't have to read anything if they were just black dots being placed in the grid. Like first set of 32 could represent the A button, second set of 32 could represent the B button, etc. As long as there was an undo for patterns you put in, it might be easier to look at to see the names of the buttons above each row of 32. Or have 33 squares across with the first square dedicated to the name of the button

**Comment by Nanobot567** [comment] 2024-04-07 04:10
Honestly 32-33 squares doesn't sound too far fetched, using that method. The problem is though, the pattern can be up to 128 steps long, which... would not fit, haha.

**Comment by Justyouraveragehomie** [comment] 2024-04-07 04:11
> The problem is though, the pattern can be up to 128 steps long 
What about separate pages then?

**Comment by Nanobot567** [comment] 2024-04-07 04:16
True, pages could work! Do you have any ideas for ways to swap pages, though? All of the input methods (a, b, left, right, up, down, crank) are already being used for stuff in the pattern editor. I suppose A or B + left/right could work but that's kind of awkward.

**Comment by Nanobot567** [comment] 2024-04-07 04:21
Oh, by the way, have you checked out the [manual](https://github.com/nanobot567/cs-16/blob/main/MANUAL.md)? I can't write documentation to save my life but it's pretty decent at explaining how CS-16 works.

**Comment by Justyouraveragehomie** [comment] 2024-04-07 04:23
Playdate does button combos? I think yeah thatd be the only way. I think most people (myself) wouldn't be making songs up to 128 likely anyways. 32 rows is pretty great especially with working with samples....in fact most drum machines don't even do that. Oh I didn't even see there was a manual, will check it out right now

**Comment by Nanobot567** [comment] 2024-04-07 04:31
> I think most people (myself) wouldn't be making songs up to 128 likely anyways.

Yeah, 128 steps is probably a bit excessive, but I will say it is nice if you want to have a chord progression or something in the song. (If you have the [Playdate Simulator](https://play.date/dev/) from the dev tools, my example song [zip-ext](https://github.com/Nanobot567/CS-16/tree/main/example-songs/zip-ext) uses all 128 steps, just for a little drum fill at the end of the pattern :laughing:)

> So thorough, very impressed

Thanks!!

**Comment by Justyouraveragehomie** [comment] 2024-04-07 04:52
Maybe a dotted grid? Where a larger dot-circle is placed overtop the dot on the dotted grid

**Comment by Nanobot567** [comment] 2024-04-07 16:57
Personally I think a squared grid looks nicer, but if it's a big design flaw in your opinion, you should fork CS-16 and make your own version!

(Just so you know [and I'm assuming that the "A" in those images means the A button], CS-16 isn't entirely based around the concept that each button corresponds to one or more instruments, rather, it's based around 16 tracks that can be edited in many different ways. Recording is just one way to add notes :) )

**Comment by Nanobot567** [comment] 2024-04-09 13:25
No, every track is in its own separate page. If you really need to see things in relation to everything else you can just flick through the tracks quickly with the crank.

**Comment by Justyouraveragehomie** [comment] 2024-06-25 04:34
Oo new version! Saw the video, looks great. The font is killing my brain though, but thats just me. Hope for a future video with the sampling shown too, like maybe sampling from vinyl using aux or something. (or the mic)

**Comment by Nanobot567** [comment] 2024-06-25 17:55
Oh, thanks! Yeah, I guess I could have used the new system font but since that font's the default I just used that one ¯\_(ツ)_/¯

**Comment by Justyouraveragehomie** [comment] 2024-06-25 22:51
I look forward to the future updates. 
Id def still show this over at https://www.reddit.com/r/PlaydateDeveloper/ to get more eyes on it!  
Close the issue if you like, you've got everything that i'd want, swing was the biggest one for me really. I just need to get myself a Playdate eventually :p

**Comment by Nanobot567** [comment] 2024-06-27 17:41
Will do! Thanks for your suggestions, and thanks again for being interested! :D

**Closed by Nanobot567** 2024-06-27 17:41 UTC
